### ISSUE TITLE
Bump iOS deployment target for example project

### ISSUE THREAD

**Issue by bbbbbrie** [joinhandshake/Querl#1]
👋 Hello, there! 

This is super cool! I started getting set up with the example project in Xcode. It's my first iOS project (😓 ) but I noticed a few things I had to change to get this working:

  - Bump `IPHONEOS_DEPLOYMENT_TARGET` to `11.0` (up from `10.0`) in a few places in a few `project.pbxproj` files
  - In `Podfile` bump the `platform` line to:

```
platform :ios, '11.0'
```

With that done, the build succeeds and the Star Wars query works! 🎉 

![Simulator Screen Shot - iPhone 14 Pro - 2023-03-03 at 21 58 12](https://user-images.githubusercontent.com/9367754/222872619-8df6246e-8f0f-4cde-8025-8a0200a80cef.png)

I'd be happy to submit a PR but the `diff` included some files that I wasn't quite expecting. 

Super cool implementation!

--
Brie 🦄 🌈

**Comment by joelk** [comment]
@bbbbbrie hi, thanks for opening the issue! I apologize for the delay, I was on vacation. I'd love to see a PR, if you have the bandwidth--we can figure out the extraneous files if they still show up.
